### ISSUE TITLE
Some arithmetic instructions don't modify the H flag

### ISSUE THREAD

**Issue by basilhussain** [mikechambers84/STM8-Emulator#12]
Several addition and subtraction instructions are supposed to change the H flag in the CC register, but I don't see any sign of code that does this. Neither `cpu_flags_arith_add()`, `cpu_flags_arith_add16()`, or `cpu_flags_arith_sub16()` appear to touch the H flag at all.

As far as I can see from looking at the Programming Manual (PM0044) document, the following instructions should be modifying the H flag:

* ADC
* ADD
* ADDW
* DIV
* DIVW
* MUL
* SUBW

But only DIV, DIVW, and MUL currently modify H (by clearing it).

**Comment by mikechambers84** [comment]
Thank you, not sure how I missed this one! I kind of rushed to get the source uploaded, and honestly have not touched it much since then, but I definitely want to get this and your other issues fixed. Some of these are major bugs.

I wanted to get into these things last weekend, but time didn't allow. This weekend is looking better.

I would also like to eventually make it easier to create "product designs", by creating a plug-in system where you could make your own DLLs similar to GPU/SPU, etc. plug-ins for game console emulators but that will take some thought to implement well. Having to add code modules and recompile the entire thing is not ideal.

**Comment by basilhussain** [comment]
Thanks for taking the time. I now also have a branch on my fork with some changes to add proper cycle timings to all instructions, but I didn't want to merge that with main branch (and thus include in the outstanding PR #8) and overwhelm you with changes. :) So I will hold off with that until you're done with the first pull request.

To be honest, I'm not personally interested in any of the 'product' stuff, but I guess it might be nice to be able to emulate entire systems. I'd be more interested in getting some other device models and peripherals working (e.g. TIM4 would be great).
